export const countries = [{ value: "pk", label: "Pakistan" }];

export const city = [
  { value: "lahore", label: "Lahore" },
  { value: "islamabad", label: "Islamabad" },
  { value: "karachi", label: "Karachi" },
  { value: "rawalpindi", label: "Rawalpindi" },
  { value: "faisalabad", label: "Faisalabad" },
  { value: "multan", label: "Multan" },
  { value: "peshawar", label: "Peshawar" },
  { value: "quetta", label: "Quetta" },
  { value: "sialkot", label: "Sialkot" },
  { value: "gujranwala", label: "Gujranwala" },
];

export const traveling = [
  { value: "Bahrain", label: "Bahrain" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Oman", label: "Oman" },
  { value: "Qatar", label: "Qatar" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "multan", label: "Multan" },
  { value: "UAE", label: "UAE" },
  { value: "Yemen", label: "Yemen" },
];

export const nationality = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "in", label: "India" },
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "in", label: "India" },
];

export const gender = [
  { value: "ma", label: "Male" },
  { value: "fe", label: "Female" },
];
export const status = [
  { value: "si", label: "Single" },
  { value: "ma", label: "Married" },
];
export const visatype = [
  { value: "si", label: "Work Visa" },
  { value: "ma", label: "Family Visa" },
];

export const position = [
  { value: "banking_and_finance", label: "Banking and Finance" },
  { value: "carpenter", label: "Carpenter" },
  { value: "cashier", label: "Cashier" },
  { value: "electrician", label: "Electrician" },
  { value: "engineer", label: "Engineer" },
  { value: "general_secretary", label: "General Secretary" },
  { value: "health_medicine_nursing", label: "Health & Medicine & Nursing" },
  { value: "heavy_driver", label: "Heavy Driver" },
  { value: "it_internet_engineer", label: "IT & Internet Engineer" },
  { value: "leisure_tourism", label: "Leisure & Tourism" },
  { value: "light_driver", label: "Light Driver" },
  { value: "mason", label: "Mason" },
  { value: "president", label: "President" },
  { value: "labour", label: "Labour" },
  { value: "plumber", label: "Plumber" },
  { value: "doctor", label: "Doctor" },
  { value: "family", label: "Family" },
  { value: "steel_fixer", label: "Steel Fixer" },
  { value: "aluminium_technician", label: "Aluminium Technician" },
  { value: "nurse", label: "Nurse" },
  { value: "male_nurse", label: "Male Nurse" },
  { value: "ward_boy", label: "Ward Boy" },
  { value: "shovel_operator", label: "Shovel Operator" },
  { value: "dozer_operator", label: "Dozer Operator" },
  { value: "car_mechanic", label: "Car Mechanic" },
  { value: "petrol_mechanic", label: "Petrol Mechanic" },
  { value: "diesel_mechanic", label: "Diesel Mechanic" },
  { value: "student", label: "Student" },
  { value: "accountant", label: "Accountant" },
  { value: "lab_technician", label: "Lab Technician" },
  { value: "draftsman", label: "Draftsman" },
  { value: "auto_cad_operator", label: "Auto-CAD Operator" },
  { value: "painter", label: "Painter" },
  { value: "tailor", label: "Tailor" },
  { value: "welder", label: "Welder" },
  { value: "x_ray_technician", label: "X-Ray Technician" },
  { value: "lecturer", label: "Lecturer" },
  { value: "ac_technician", label: "A.C Technician" },
  { value: "business", label: "Business" },
  { value: "cleaner", label: "Cleaner" },
  { value: "security_guard", label: "Security Guard" },
  { value: "house_maid", label: "House Maid" },
  { value: "manager", label: "Manager" },
  { value: "hospital_cleaning", label: "Hospital Cleaning" },
  { value: "mechanic", label: "Mechanic" },
  { value: "computer_operator", label: "Computer Operator" },
  { value: "house_driver", label: "House Driver" },
  { value: "driver", label: "Driver" },
  { value: "cleaning_labour", label: "Cleaning Labour" },
  { value: "building_electrician", label: "Building Electrician" },
  { value: "salesman", label: "Salesman" },
  { value: "plaster_mason", label: "Plaster Mason" },
  { value: "servant", label: "Servant" },
  { value: "barber", label: "Barber" },
  { value: "residence", label: "Residence" },
  { value: "shepherds", label: "Shepherds" },
  { value: "employment", label: "Employment" },
  { value: "fuel_filler", label: "Fuel Filler" },
  { value: "worker", label: "Worker" },
  { value: "house_boy", label: "House Boy" },
  { value: "house_wife", label: "House Wife" },
  { value: "rcc_fitter", label: "RCC Fitter" },
  { value: "clerk", label: "Clerk" },
  { value: "microbiologist", label: "Microbiologist" },
  { value: "teacher", label: "Teacher" },
  { value: "helper", label: "Helper" },
  { value: "hajj_duty", label: "Hajj Duty" },
  { value: "shuttering", label: "Shuttering" },
  { value: "supervisor", label: "Supervisor" },
  { value: "medical_specialist", label: "Medical Specialist" },
  { value: "office_secretary", label: "Office Secretary" },
  { value: "technician", label: "Technician" },
  { value: "butcher", label: "Butcher" },
  { value: "arabic_food_cook", label: "Arabic Food Cook" },
  { value: "agricultural_worker", label: "Agricultural Worker" },
  { value: "service", label: "Service" },
  { value: "studio_cad_designer", label: "Studio CAD Designer" },
  { value: "financial_analyst", label: "Financial Analyst" },
  {
    value: "cabin_appearance_air_lines",
    label: "Cabin Appearance (Air Lines)",
  },
  { value: "car_washer", label: "Car Washer" },
  { value: "surveyor", label: "Surveyor" },
  { value: "electrical_technician", label: "Electrical Technician" },
  { value: "waiter", label: "Waiter" },
  { value: "nursing_helper", label: "Nursing Helper" },
  { value: "anaesthesia_technician", label: "Anaesthesia Technician" },
  { value: "marvel", label: "Marvel" },
  { value: "construction_worker", label: "Construction Worker" },
];
